<?php
namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Seeder;

class QuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $questions = [
            [
                'id_quiz' => 1,
                'nb_question' => 1,
                'name_question' => 'What keyword is used to declare a variable in JavaScript?',
                'f_answer' => 'let',
                's_answer' => 'var',
                't_answer' => 'const',
                'fth_answer' => 'All of the above',
                'real_answer' => 'All of the above',
            ],
            [
                'id_quiz' => 1,
                'nb_question' => 2,
                'name_question' => 'What is the output of console.log(typeof []) ?',
                'f_answer' => '"array"',
                's_answer' => '"object"',
                't_answer' => '"undefined"',
                'fth_answer' => '"function"',
                'real_answer' => '"object"',
            ],
            [
                'id_quiz' => 1,
                'nb_question' => 3,
                'name_question' => 'How do you write a single-line comment in JavaScript?',
                'f_answer' => '# This is a comment',
                's_answer' => '/* This is a comment */',
                't_answer' => '// This is a comment',
                'fth_answer' => '-- This is a comment',
                'real_answer' => '// This is a comment',
            ],
            [
                'id_quiz' => 1,
                'nb_question' => 4,
                'name_question' => "What does the expression Boolean('false') return?",
                'f_answer' => 'true',
                's_answer' => 'false',
                't_answer' => 'undefined',
                'fth_answer' => 'NaN',
                'real_answer' => 'true',
            ],
            [
                'id_quiz' => 1,
                'nb_question' => 5,
                'name_question' => 'Which method is used to add an element to the end of an array in JavaScript?',
                'f_answer' => '.push()',
                's_answer' => '.pop()',
                't_answer' => '.shift()',
                'fth_answer' => '.unshift()',
                'real_answer' => '.push()',
            ],
            [
                'id_quiz' => 1,
                'nb_question' => 6,
                'name_question' => "What is the output of console.log(2 + '2') ?",
                'f_answer' => '4',
                's_answer' => '22',
                't_answer' => 'NaN',
                'fth_answer' => 'TypeError',
                'real_answer' => '22',
            ],
            [
                'id_quiz' => 1,
                'nb_question' => 7,
                'name_question' => 'Which structure is used to execute code repeatedly?',
                'f_answer' => 'if',
                's_answer' => 'switch',
                't_answer' => 'loop',
                'fth_answer' => 'for',
                'real_answer' => 'for',
            ],
            [
                'id_quiz' => 1,
                'nb_question' => 8,
                'name_question' => 'Which object is used to manipulate dates in JavaScript?',
                'f_answer' => 'Date',
                's_answer' => 'Time',
                't_answer' => 'Clock',
                'fth_answer' => 'Calendar',
                'real_answer' => 'Date',
            ],
            [
                'id_quiz' => 1,
                'nb_question' => 9,
                'name_question' => 'What does the JSON.stringify() method do?',
                'f_answer' => 'Converts a JavaScript object to a JSON string',
                's_answer' => 'Converts a JSON string to a JavaScript object',
                't_answer' => 'Checks if a string is in JSON format',
                'fth_answer' => 'None of the above',
                'real_answer' => 'Converts a JavaScript object to a JSON string',
            ],
            [
                'id_quiz' => 1,
                'nb_question' => 10,
                'name_question' => 'What is the difference between == and === in JavaScript?',
                'f_answer' => 'No difference',
                's_answer' => '== compares values only, while === compares both values and types',
                't_answer' => '=== compares values only',
                'fth_answer' => '== compares memory references',
                'real_answer' => '== compares values only, while === compares both values and types',
            ],
            [
                'id_quiz' => 2,
                'nb_question' => 1,
                'name_question' => 'What is the role of HTML?',
                'f_answer' => 'Defines the structure of a webpage',
                's_answer' => 'Applies style to webpages',
                't_answer' => 'Adds interactivity',
                'fth_answer' => 'Stores data',
                'real_answer' => 'Defines the structure of a webpage',
            ],
            [
                'id_quiz' => 2,
                'nb_question' => 2,
                'name_question' => 'What is the correct tag to insert an image in HTML?',
                'f_answer' => '<image>',
                's_answer' => '<img>',
                't_answer' => '<picture>',
                'fth_answer' => '<photo>',
                'real_answer' => '<img>',
            ],
            [
                'id_quiz' => 2,
                'nb_question' => 3,
                'name_question' => 'Which tag is used to create a hyperlink?',
                'f_answer' => '<link>',
                's_answer' => '<a>',
                't_answer' => '<href>',
                'fth_answer' => '<url>',
                'real_answer' => '<a>',
            ],
            [
                'id_quiz' => 2,
                'nb_question' => 4,
                'name_question' => 'What is the basic structure of an HTML document?',
                'f_answer' => '<html><head><title></title></head><body></body></html>',
                's_answer' => '<header><body><footer>',
                't_answer' => '<main><article><section>',
                'fth_answer' => '<head><content><footer>',
                'real_answer' => '<html><head><title></title></head><body></body></html>',
            ],
            [
                'id_quiz' => 2,
                'nb_question' => 5,
                'name_question' => 'Which tag is used to insert an unordered list?',
                'f_answer' => '<ol>',
                's_answer' => '<ul>',
                't_answer' => '<li>',
                'fth_answer' => '<list>',
                'real_answer' => '<ul>',
            ],
            [
                'id_quiz' => 2,
                'nb_question' => 6,
                'name_question' => 'How do you create an input field for a form in HTML?',
                'f_answer' => '<text>',
                's_answer' => '<input type="text">',
                't_answer' => '<textbox>',
                'fth_answer' => '<field>',
                'real_answer' => '<input type="text">',
            ],
            [
                'id_quiz' => 2,
                'nb_question' => 7,
                'name_question' => 'Which tag is used to create a table in HTML?',
                'f_answer' => '<table>',
                's_answer' => '<tr>',
                't_answer' => '<td>',
                'fth_answer' => '<tab>',
                'real_answer' => '<table>',
            ],
            [
                'id_quiz' => 2,
                'nb_question' => 8,
                'name_question' => 'Which attribute allows you to open a link in a new tab?',
                'f_answer' => 'target="_self"',
                's_answer' => 'target="_new"',
                't_answer' => 'target="_blank"',
                'fth_answer' => 'target="new_tab"',
                'real_answer' => 'target="_blank"',
            ],
            [
                'id_quiz' => 2,
                'nb_question' => 9,
                'name_question' => 'Which tag is used to define a navigation section?',
                'f_answer' => '<nav>',
                's_answer' => '<menu>',
                't_answer' => '<section>',
                'fth_answer' => '<header>',
                'real_answer' => '<nav>',
            ],
            [
                'id_quiz' => 2,
                'nb_question' => 10,
                'name_question' => 'What is the correct semantics for a first-level heading in HTML?',
                'f_answer' => '<head>',
                's_answer' => '<title>',
                't_answer' => '<h1>',
                'fth_answer' => '<header>',
                'real_answer' => '<h1>',
            ],
            [
                'id_quiz' => 3,
                'nb_question' => 1,
                'name_question' => 'What does CSS stand for?',
                'f_answer' => 'Creative Style Sheets',
                's_answer' => 'Cascading Style Sheets',
                't_answer' => 'Computer Styled Sections',
                'fth_answer' => 'Colorful Style Sheets',
                'real_answer' => 'Cascading Style Sheets',
            ],
            [
                'id_quiz' => 3,
                'nb_question' => 2,
                'name_question' => 'Which CSS property is used to change the text color?',
                'f_answer' => 'text-color',
                's_answer' => 'color',
                't_answer' => 'font-color',
                'fth_answer' => 'text-style',
                'real_answer' => 'color',
            ],
            [
                'id_quiz' => 3,
                'nb_question' => 3,
                'name_question' => 'Which CSS selector is used to target an element with id="menu"?',
                'f_answer' => '.menu',
                's_answer' => '#menu',
                't_answer' => 'menu',
                'fth_answer' => '*menu*',
                'real_answer' => '#menu',
            ],
            [
                'id_quiz' => 3,
                'nb_question' => 4,
                'name_question' => 'Which of these CSS rules adds 10px of padding inside an element?',
                'f_answer' => 'margin: 10px;',
                's_answer' => 'padding: 10px;',
                't_answer' => 'spacing: 10px;',
                'fth_answer' => 'border-spacing: 10px;',
                'real_answer' => 'padding: 10px;',
            ],
            [
                'id_quiz' => 3,
                'nb_question' => 5,
                'name_question' => 'What is the effect of display: flex; on an element?',
                'f_answer' => 'It prevents the element from being displayed',
                's_answer' => 'It aligns child elements in a row or column',
                't_answer' => 'It turns the element into a table',
                'fth_answer' => 'It forces the element to take up the full width',
                'real_answer' => 'It aligns child elements in a row or column',
            ],
            [
                'id_quiz' => 3,
                'nb_question' => 6,
                'name_question' => 'Which CSS property is used to round the corners of an element?',
                'f_answer' => 'corner-radius',
                's_answer' => 'border-radius',
                't_answer' => 'rounding',
                'fth_answer' => 'border-style',
                'real_answer' => 'border-radius',
            ],
            [
                'id_quiz' => 3,
                'nb_question' => 7,
                'name_question' => 'Which position value allows an element to stay fixed at the top of the page while scrolling?',
                'f_answer' => 'relative',
                's_answer' => 'absolute',
                't_answer' => 'fixed',
                'fth_answer' => 'static',
                'real_answer' => 'fixed',
            ],
            [
                'id_quiz' => 3,
                'nb_question' => 8,
                'name_question' => 'Which property is used to add a shadow to text in CSS?',
                'f_answer' => 'text-decoration',
                's_answer' => 'text-shadow',
                't_answer' => 'box-shadow',
                'fth_answer' => 'shadow-effect',
                'real_answer' => 'text-shadow',
            ],
            [
                'id_quiz' => 3,
                'nb_question' => 9,
                'name_question' => 'Which CSS rule is used to apply a style only when the user hovers over an element?',
                'f_answer' => ':focus',
                's_answer' => ':visited',
                't_answer' => ':hover',
                'fth_answer' => ':active',
                'real_answer' => ':hover',
            ],
            [
                'id_quiz' => 3,
                'nb_question' => 10,
                'name_question' => 'Which CSS unit is relative to the parent element\'s font size?',
                'f_answer' => 'px',
                's_answer' => 'em',
                't_answer' => '%',
                'fth_answer' => 'vh',
                'real_answer' => 'em',
            ],
            [
                'id_quiz' => 4,
                'nb_question' => 1,
                'name_question' => 'What is web accessibility?',
                'f_answer' => 'A set of rules to make a website faster',
                's_answer' => 'Adapting websites for users with disabilities',
                't_answer' => 'A principle to improve search engine optimization',
                'fth_answer' => 'A technology for creating animations',
                'real_answer' => 'Adapting websites for users with disabilities',
            ],
            [
                'id_quiz' => 4,
                'nb_question' => 2,
                'name_question' => 'Which HTML tag is used to provide alternative text for images?',
                'f_answer' => 'title',
                's_answer' => 'alt',
                't_answer' => 'aria-label',
                'fth_answer' => 'desc',
                'real_answer' => 'alt',
            ],
            [
                'id_quiz' => 4,
                'nb_question' => 3,
                'name_question' => 'What does WCAG stand for?',
                'f_answer' => 'Web Content Accessibility Guidelines',
                's_answer' => 'Web Compliance and Accessibility Guide',
                't_answer' => 'Worldwide Content Accessibility Guide',
                'fth_answer' => 'Web Color Accessibility Guidelines',
                'real_answer' => 'Web Content Accessibility Guidelines',
            ],
            [
                'id_quiz' => 4,
                'nb_question' => 4,
                'name_question' => 'Which text color provides the best contrast on a white background?',
                'f_answer' => 'Yellow',
                's_answer' => 'Light blue',
                't_answer' => 'Black',
                'fth_answer' => 'Light gray',
                'real_answer' => 'Black',
            ],
            [
                'id_quiz' => 4,
                'nb_question' => 5,
                'name_question' => 'Which ARIA attribute is used to define a text alternative when no visible text is available?',
                'f_answer' => 'aria-hidden',
                's_answer' => 'aria-label',
                't_answer' => 'aria-description',
                'fth_answer' => 'alt',
                'real_answer' => 'aria-label',
            ],
            [
                'id_quiz' => 4,
                'nb_question' => 6,
                'name_question' => 'What does keyboard navigation allow?',
                'f_answer' => 'Navigating only in forms',
                's_answer' => 'Navigating a website without using the mouse',
                't_answer' => 'Modifying page displays',
                'fth_answer' => 'Using keyboard shortcuts to code',
                'real_answer' => 'Navigating a website without using the mouse',
            ],
            [
                'id_quiz' => 4,
                'nb_question' => 7,
                'name_question' => 'Why is it important to use semantic HTML tags (<header>, <nav>, <main>, <footer>)?',
                'f_answer' => 'To better structure the page and improve accessibility',
                's_answer' => 'To make the website faster',
                't_answer' => 'To avoid using CSS',
                'fth_answer' => 'To add animations',
                'real_answer' => 'To better structure the page and improve accessibility',
            ],
            [
                'id_quiz' => 4,
                'nb_question' => 8,
                'name_question' => 'What is essential to make a website accessible to visually impaired users?',
                'f_answer' => 'A colorful design',
                's_answer' => 'Text that is readable with good contrast',
                't_answer' => 'Fancy fonts',
                'fth_answer' => 'Large images',
                'real_answer' => 'Text that is readable with good contrast',
            ],
            [
                'id_quiz' => 4,
                'nb_question' => 9,
                'name_question' => 'Which CSS property improves readability for dyslexic people?',
                'f_answer' => 'letter-spacing: 0;',
                's_answer' => 'font-family: Arial, sans-serif;',
                't_answer' => 'text-transform: uppercase;',
                'fth_answer' => 'word-spacing: 2px;',
                'real_answer' => 'font-family: Arial, sans-serif;',
            ],
            [
                'id_quiz' => 4,
                'nb_question' => 10,
                'name_question' => 'Which tool can be used to test the accessibility of a website?',
                'f_answer' => 'Google PageSpeed',
                's_answer' => 'Lighthouse',
                't_answer' => 'Photoshop',
                'fth_answer' => 'Figma',
                'real_answer' => 'Lighthouse',
            ]
        ];

        foreach ($questions as $question) {
            Question::create($question);
        }
    }
}
